### PR TITLE
Added zabbix agent as optional feed package

### PR DESCRIPTION
**Pull request by petrkr**
Added zabbix agent binary, useful for monitoring stb

### CODE REVIEW

**Comment by persianpros** [comment]
I will add it ok but in alphabetical order ;)

**Comment by petrkr** [comment]
3 times I must look again why you wrote that... and now noticed that package is YA not ZA :) 
overlook when I added, of course I want that in alphabetical order :)

**Comment by persianpros** [comment]
I can't help it but I have good eyes :D

**Comment by petrkr** [comment]
Or maybe you not did 4 other things during work hours :)

**Pull request closed without merging**
